from pydantic import BaseModel, Field
from typing import Dict, Any
from backend.tools.registry import registry
import markdown
import os
from backend.core.config import settings
import uuid

# Try to import WeasyPrint, handle failure gracefully
try:
    from weasyprint import HTML
    WEASYPRINT_AVAILABLE = True
except OSError:
    print("⚠️ WeasyPrint dependencies (pango/cairo/gobject) missing. PDF generation disabled.")
    WEASYPRINT_AVAILABLE = False
except ImportError:
    WEASYPRINT_AVAILABLE = False

class ReportGenRequest(BaseModel):
    title: str = Field(..., description="Report Title")
    content_markdown: str = Field(..., description="The body content in Markdown format")
    author: str = Field("Lexi Prime", description="Author Name")

@registry.register(
    tool_id="report_generator",
    name="Report Generator (PDF)",
    description="Generates a professional PDF report from Markdown content.",
    input_model=ReportGenRequest
)
async def generate_report_pdf(params: Dict[str, Any]) -> Dict[str, str]:
    req = ReportGenRequest(**params)
    
    reports_dir = os.path.join(settings.BASE_DIR, "data", "reports")
    os.makedirs(reports_dir, exist_ok=True)
    
    # 1. Convert Markdown to HTML
    html_body = markdown.markdown(req.content_markdown)
    
    # 2. Template (Minimal)
    full_html = f"""
    <html>
    <body>
        <h1>{req.title}</h1>
        <div class="meta">Generated by {req.author}</div>
        {html_body}
    </body>
    </html>
    """
    
    if WEASYPRINT_AVAILABLE:
        filename = f"report_{uuid.uuid4().hex[:8]}.pdf"
        file_path = os.path.join(reports_dir, filename)
        HTML(string=full_html).write_pdf(file_path)
        return {"status": "success", "file_path": file_path, "type": "pdf"}
    else:
        # Fallback to HTML if PDF engine fails
        filename = f"report_{uuid.uuid4().hex[:8]}.html"
        file_path = os.path.join(reports_dir, filename)
        with open(file_path, "w") as f:
            f.write(full_html)
        return {"status": "partial_success", "file_path": file_path, "type": "html", "note": "PDF engine missing, saved as HTML"}
